<div class="usvn_info">
	<h1><?php echo T_("Homepage"); ?></h1>
</div>
<div id="usvn_index_projects" class="usvn_index_box">
	<h3><?php echo T_("Your projects"); ?>:</h3>
<?php if (count($this->projects)): ?>
    <ul class="grid_list">
	<?php foreach ($this->projects as $project): ?>
		<li>
			<a href="<?php echo $this->url(array('project' => $project->name), 'project'); ?>">
				<div class="grid_img">
					<?php echo $this->img('box48.png'); ?>
				</div>
				<div title="<?php echo htmlentities($project->name, ENT_QUOTES) ?>"><?php echo $project->name; ?></div>
			</a>
		</li>
	<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p><?php echo T_("You don't have any project."); ?></p>
<?php endif; ?>
</div>
<div id="usvn_index_groups" class="usvn_index_box">
	<h3><?php echo T_("Your groups"); ?>:</h3>
<?php if (count($this->groups)): ?>
	<ul class="grid_list">
	<?php foreach ($this->groups as $group): ?>
		<li>
			<a href="<?php echo $this->url(array('group' => $group->name), 'group'); ?>">
				<div class="grid_img">
					<?php echo $this->img('group48.png'); ?>
				</div>
				<div><?php echo $group->name; ?></div>
			</a>
		</li>
	<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p><?php echo T_("You are not assign to a group."); ?></p>
<?php endif; ?>
</div>
<div style="clear: both;">
	<img width="1" height="1" src="<?php echo $this->url(array('controller' => 'checkupdate')); ?>" />
</div>
